[package]
name = "blunux-setup"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "blunux-setup"
path = "src/main.rs"

[dependencies]
blunux-config = { path = "../blunux-config" }
clap = { version = "4", features = ["derive"] }
anyhow = "1"
